services:
  - type: web
    name: xmall
    env: docker
    plan: free
    dockerfilePath: Dockerfile 
    dockerContext: .  # Contexte racine
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: APP_SECRET
        sync: false  # Ajoute dans dashboard (random 32 chars)
      - key: DATABASE_URL
        value: sqlite:///%kernel.project_dir%/var/data.db
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
