services:
  - type: web
    name: xmall
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: APP_SECRET
        sync: false  # Ajoute ton secret dans dashboard
      - key: DATABASE_URL
        value: sqlite:///%kernel.project_dir%/var/data.db
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: PORT
        value: 10000  # Fix port scan
